base_config:
  - ./base.yaml

raw_data_dir: data/raw/ted
processed_data_dir: data/processed/ted
binary_data_dir: data/binary/ted
ds_names_in_training: ''  # ';' separated
ds_names_in_testing: ''   # default: '', means all in testing
noise_data_dir: data/binary/musan_24k

binarizer_cls: data_gen.ted_binarizer.TechExtractionBinarizer
binarization_args:
  with_wav: true
  with_mel: false
  with_breathiness: true
  with_energy: true
  with_zcr: true

task_cls: tasks.TechDet.ted_task.TETask

test_prefixes: [
  "华为女声#假声#单身情歌",
  "华为女声#气泡音#单身情歌",
  "华为女声#气声#岁月神偷",
  "华为男声#力度#爱情转移",
  "华为男声#气泡音#安河桥",
  "华为男声#气声#暗香",
  "Chinese#ZH-Tenor-1#Breathy#不染",
  "Chinese#ZH-Alto-1#Pharyngeal#不为谁而作的歌",
  "Chinese#ZH-Alto-1#Vibrato#不再见",
  "Chinese#ZH-Alto-1#Glissando#传奇",
  "Chinese#ZH-Alto-1#Mixed_Voice_and_Falsetto#一次就好",

  "English#EN-Alto-1#Breathy#all is found",
  "English#EN-Alto-1#Pharyngeal#beauty and the beast",
  "English#EN-Alto-2#Vibrato#A Thousand Years",
  "English#EN-Alto-2#Glissando#A Thousand Years",
  "English#EN-Alto-2#Mixed_Voice_and_Falsetto#All of Me",

  "Spanish#ES-Bass-1#Mixed_Voice_and_Falsetto#Aire",
  "German#DE-Tenor-1#Mixed_Voice_and_Falsetto#An die Laute",
  "French#FR-Tenor-1#Mixed_Voice_and_Falsetto#Le Toréador",
  "Russian#RU-Alto-1#Mixed_Voice_and_Falsetto#Аня Облонская",
  "Japanese#JA-Tenor-1#Mixed_Voice_and_Falsetto#Heartful song",
  "Korean#KO-Soprano-1#Mixed_Voice_and_Falsetto#all with you",
  "Italian#IT-Bass-1#Mixed_Voice_and_Falsetto#Gioia dell'amore"
]
audio_sample_rate: 48000
hop_size: 256
win_size: 1024
fft_size: 1024
fmax: 24000
fmin: 20
dropout: 0.1
hidden_size: 256

###########
# model related params
###########
model: te
squeezeformer_kernel: 9
updown_rates: 2-2-2
channel_multiples: 1-1-1
bkb_net: squeezeformer
bkb_layers: 2
unet_skip_layer: false
unet_skip_scale: 0.7071067812   # 1 / sqrt(2)

###########
# tech prediction related hparams
###########
# f0
f0_add_noise: gaussian:0.04  # gaussian:0.04
# pitch
pe: rmvpe  # rmvpe|parselmouth|pw
pe_ckpt: checkpoints/rmvpe/model.pt
f0_bin: 256
f0_filepath: ''
use_pitch_embed: true
# tech
tech_num: 6
tech_threshold: 0.8
#tech_label_smoothing: 0.005
tech_temperature: 0.01
tech_attn_num_head: 4
tech_focal_loss: 5.0
# lambdas
lambda_tech: 1.0
lambdas_tech: ''  # lambdas jointed with '-'
lambda_tech_focal: 3.0
label_pos_weight_decay: 0.95

###########
# noise
###########
noise_snr: 6-20
noise_prob: 0.8
noise_in_test: false

loud_norm: true
use_mel: true
use_mel_bins: 80
mel_add_noise: gaussian:0.05 # gaussian|none|musan
use_wav: false
use_f0: true
dataset_downsample_rate: 1.0

lr: 0.000005
scheduler: step_lr
scheduler_lr_step_size: 500
warmup_updates: 0

max_epochs: 1000
save_best: true
num_valid_plots: 10
accumulate_grad_batches: 4
find_unused_parameters: true
pin_memory: true
ds_workers: 8
torch_compile: false

apply_neg_sampling: true
apply_tech_group_loss: true
apply_weighted_sampler: false

use_breathiness: true
breathiness_add_noise: gaussian:0.04
use_energy: true
energy_add_noise: gaussian:0.04
use_zcr: true
zcr_add_noise: gaussian:0.01
frames_multiple: 8

max_sentences: 8
max_tokens: 20000
max_updates: 120000
max_frames: 20000
val_check_interval: 2000
num_valid_stats: 2000